version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: nginx
    networks:
      - main
    restart: on-failure
    ports:
      - 80:8080
    environment:
      - PORT=8080

networks:
  main:
